spring:
  application:
    name: lovable-clone
    description: Lovable application

  datasource:
    url: jdbc:postgresql://localhost:5432/Lovable
    username: sankalp
    password: Sankalp
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true